# google spreadsheets constants

CLIENT_SECRET_PATH = 'secrets/desktop_client_secret.json'

RADIK_SPREADSHEET_ID = '1XjWVL7QN2WIW1JS41potqEoxyXFKOPQ3b7DptBk0wa0'
DINARA_SPREADSHEET_ID = '1CNFEEKwsiLghqH6JigCCHVjyxTct1hNePTj57K9BOrM'
SEREBRYANICHESKIY_SPREADSHEET_ID = '1-0_Isxce-OCApHlFVI1e734O9SQO9qRPDMR-Gkzm-5Y'
CONFIG_SPREADSHEET = 'record-bookings'

CONFIG_WORKSHEET = 'Объекты'
BOOKINGS_CONFIG_WORKSHEET = 'Приходы'
EXPENSES_CONFIG_WORKSHEET = 'Расходы'
SPREADSHEET_CONFIG_WORKSHEET = 'Таблицы'

RADIK = 'Основная'
DINARA = 'Никитская'
SEREBRYANICHESKIY = 'Серебрянический'

TEMPLATE_WORKSHEET = 'Бланк'

TEMPLATE_WORKSHEETS = {
    '1XjWVL7QN2WIW1JS41potqEoxyXFKOPQ3b7DptBk0wa0': 'Бланк 2022',
    '1CNFEEKwsiLghqH6JigCCHVjyxTct1hNePTj57K9BOrM': 'Бланк 2022',
    '1-0_Isxce-OCApHlFVI1e734O9SQO9qRPDMR-Gkzm-5Y': 'Бланк',
}

# bookings
SPREADSHEET_MAPPINGS: {
    RADIK: RADIK_SPREADSHEET_ID,
    DINARA: DINARA_SPREADSHEET_ID,
    SEREBRYANICHESKIY: SEREBRYANICHESKIY_SPREADSHEET_ID,
}

# expenses

EXPENSES_SPREADSHEET_ID = '122tDi9ZilIuyi_mPe5yIVBggfkQdS9h0I1WtnskHlzU'

# bnova spreadsheet constants

DIRECT = 'Прямой'
SUTOCHNO = 'Sutochno'
OSTROVOK = 'Ostrovok'

COMMISSION_MAP = {
    DIRECT: 0,
    SUTOCHNO: 0.25,
    OSTROVOK: 0.15,
}

BNOVA_SHEET_NAME = 'Бронирования'
