# google spreadsheets constants

CLIENT_SECRET_PATH = 'secrets/desktop_client_secret.json'

RADIK_SPREADSHEET_ID = '1XjWVL7QN2WIW1JS41potqEoxyXFKOPQ3b7DptBk0wa0'
DINARA_SPREADSHEET_ID = '1CNFEEKwsiLghqH6JigCCHVjyxTct1hNePTj57K9BOrM'
SEREBRYANICHESKIY_SPREADSHEET_ID = '1-0_Isxce-OCApHlFVI1e734O9SQO9qRPDMR-Gkzm-5Y'

SPREADSHEETS_MAP = {
    'RADIK': RADIK_SPREADSHEET_ID,
    'DINARA': DINARA_SPREADSHEET_ID,
    'SEREBRYANICHESKIY': SEREBRYANICHESKIY_SPREADSHEET_ID,
}


# bnova spreadsheet constants

DIRECT = 'Прямой'
SUTOCHNO = 'Sutochno'
OSTROVOK = 'Ostrovok (Emerging Travel Group)'

SOURCES = [DIRECT, SUTOCHNO, OSTROVOK]

COMMISSION_MAP = {
    DIRECT: 0,
    SUTOCHNO: 0.25,
    OSTROVOK: 0.15,
}

BNOVA_SHEET_NAME = 'Бронирования'
